name: smartpay
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  
  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  turkmen_localization_support: ^0.0.8
  slang: ^4.3.0
  slang_flutter: ^4.3.0
  slang_build_runner: ^4.3.0

  # Utility
  get_it: ^8.0.2
  
  # Model
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  shared_preferences: ^2.3.3
  
  # View-Model
  mobx: ^2.4.0
  flutter_mobx: ^2.2.1+1

  # View

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # Code generation
  build_runner: ^2.4.13
  mobx_codegen: ^2.6.2

  # Model
  json_serializable: ^6.9.0
  
  # Utility
  icons_launcher: ^3.0.0

flutter:
  uses-material-design: true

icons_launcher:
  image_path: "assets/application/smartpay_logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
